version: 2

project_name: kdescribe

before:
  hooks:
    - go mod tidy

builds:
  - id: kubectl-kdescribe
    binary: kubectl-kdescribe
    main: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: kdescribe
    ids:
      - kubectl-kdescribe
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- .Arch }}
    files:
      - LICENSE
      - README.md

checksum:
  name_template: checksums.txt
